twig:
    form_themes:
        - '@LeaptFroalaEditor/Form/froala_widget.html.twig'

leapt_froala_editor:
    language: en
    toolbarInline: true
    tableColors: [ '#FFFFFF', '#FF0000' ]
    saveParams: { "id" : "myEditorField" }
