security:
    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 
            algorithm: 'auto'
            cost: 15
            
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                invalidate_session: true

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800     # 1 week in seconds (7 * 24 * 60 * 60)
                path: /
                #always_remember_me: true

        # Separate firewall for employer login (optional but can be beneficial for clarity)
        employer:
            lazy: true
            pattern: ^/employer
            provider: app_user_provider
            custom_authenticator:
                - App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                invalidate_session: true

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /


    access_control:
    - { path: ^/home, roles: PUBLIC_ACCESS }
    - { path: ^/auth, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: [ROLE_USER, ROLE_SUPER_ADMIN] }

    # Employer access control
    - { path: ^/employer/profile-image, roles: PUBLIC_ACCESS }
    - { path: ^/employer, roles: [ROLE_USER, ROLE_SUPER_ADMIN] }

    # Jobseeker access control
    - { path: ^/jobseeker/pricing, roles: PUBLIC_ACCESS }
    - { path: ^/jobseeker/job_details, roles: PUBLIC_ACCESS }
    - { path: ^/jobseeker/course_details, roles: PUBLIC_ACCESS }
    - { path: ^/jobseeker/serveFiles, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/jobseeker/downloadPurchasedFile, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/jobseeker/tender_details, roles: PUBLIC_ACCESS }
    - { path: ^/jobseeker/checkout, roles: PUBLIC_ACCESS }
    - { path: ^/jobseeker, roles: ROLE_JOBSEEKER }

    # Public access for profile images
    - { path: ^/profile-image, roles: PUBLIC_ACCESS }
    - { path: ^/sitemap.xml, roles: PUBLIC_ACCESS }
    - { path: ^/robots.txt, roles: PUBLIC_ACCESS }


    # Adjust for tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
